import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { notFound, redirect } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { ReturnNav } from "@/components/return-nav";
import { Badge, Button, Card, Input } from "@/components/ui";
import { ValidationIssue } from "@/components/validation-issue";
import { json, inr, maskAccount, maskPan } from "@/lib/utils";
import type { TaxComputation } from "@/lib/tax/engine";
import Link from "next/link";
import { overviewFromRecords, parsePreparation, type PrefillEntry } from "@/lib/documents/prefill";
import { PrepareSummary } from "@/components/prepare-summary";
import { generateJsonAction } from "@/app/json-actions";
import { resolveConflictAction } from "@/app/actions";
import { canGenerateItrJson } from "@/lib/itr-json/mapper";
import { reviewReadiness } from "@/lib/review/readiness";
import { getUserAccess } from "@/lib/plan";
import { ProUpgradeCard } from "@/components/upgrade-cta";
