import schema from "../src/lib/itr-json/schemas/ay2026_27/itr4/schema.json";
const defs = (schema as { definitions: Record<string, any> }).definitions;
console.log("CodeAD", JSON.stringify(defs.NatOfBus44AD.properties.CodeAD, null, 2).slice(0, 2000));
console.log("CodeADA", JSON.stringify(defs.NatOfBus44ADA.properties, null, 2).slice(0, 1500));
console.log("PropertyDetails required", defs.PropertyDetails.required);
console.log("ifLetOut", JSON.stringify(defs.PropertyDetails.properties.ifLetOut));
console.log("Rentdetails required", defs.Rentdetails.required);
console.log("AddtnlBankDetails items", JSON.stringify(defs.BankAccountDtls, null, 2).slice(0, 800));
console.log("Digest", JSON.stringify(defs.CreationInfo.properties.Digest));
console.log("SWCreatedBy", JSON.stringify(defs.CreationInfo.properties.SWCreatedBy));
console.log("JSONCreatedBy", JSON.stringify(defs.CreationInfo.properties.JSONCreatedBy));
console.log("SWVersionNo", JSON.stringify(defs.CreationInfo.properties.SWVersionNo));
console.log("Form Description max", defs.Form_ITR4.properties.Description);
console.log("FormName", JSON.stringify(defs.Form_ITR4.properties.FormName));
console.log("AssessmentYear", JSON.stringify(defs.Form_ITR4.properties.AssessmentYear));
console.log("ItrFilingDueDate", JSON.stringify(defs.FilingStatus.properties.ItrFilingDueDate));
console.log("additionalProperties root", (schema as any).additionalProperties);
console.log("ITR4 additionalProperties", defs.ITR4.additionalProperties);
console.log("ITR additionalProperties", defs.ITR.additionalProperties);
